services:
  - type: web
    name: sinhala-phishing-backend
    runtime: python
    plan: free
    region: singapore # or frankfurt / oregon
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: python -m backend.app.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
