services:
  - type: web
    name: sinhala-phishing-backend
    runtime: python
    plan: free
    region: singapore # or frankfurt / oregon
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "1"
